erDiagram
    CREATURES{
      expression id PK "Autoinc"
      expression HP
      expression AC
      expression STR
      expression DEX
      expression CON
      expression INT
      expression WIS 
      expression CHA
    }

    VARIABLES{
      String tag PK
      int value
      String name
    }